### PR TITLE
Like counter

### PR DESCRIPTION
**Pull request by Dorcas126**
# Add item counter to homepage

We created a specific function to calculate it.

 - correct number is displayed on the Homepage.

 # We followed the following rules:
- Each counter should be implemented as a separate module.
- A counter function should look for specific DOM elements (e.g. for the comments counter it should look for comments) and - make the counting based on what is actually displayed on the page.
- A counter function should cover all the edge.

### CODE REVIEW

**Comment by Dorcas126** [comment]
Hi @AsumVictor . I'm done with the like counter functionality. However, I am facing with API and I would be happy if you could help me with that. Thank you

**Comment by AsumVictor** [comment]
Okay @Dorcas126, Great for implementing the like counter feature. Sorry for facing such issues. Let me fetch the branch and let all solve it together. Thank you.

**Comment by Dorcas126** [comment]
> Okay @Dorcas126, Great for implementing the like counter feature. Sorry for facing such issues. Let me fetch the branch and let all solve it together. Thank you.

Thank you👍

**Review by AsumVictor — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @Dorcas126 , 👋 👋  

Thank you for making the necessary changes. I think the code is clean and complete. We can merge it and continue the next task🥇. Congratulations!  🎉💯🌟 




## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Implement the like counter on the homepage ✔️
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
