### PR TITLE
JavaScript Capstone Project

### PR DESCRIPTION
**Pull request by Dorcas126**
The JavaScript capstone project is about building our own web application based on an external API. We will select an API that provides data about a topic we like and then build the web app around it.

- A home page showing a list of items
- A popup window with more data about an item that we can use to comment on it or reserve it for a period of time.

### CODE REVIEW

**Review by AsumVictor — COMMENTED** [review]
Hi @Dorcas126,
You have done an amazing job of setting up the files for the capstone projects. However, I would like to add a few changes to the webpack configuration before we merge it. 

##Changes
- [ ] I would like to create a config file for development mode and production mode.
- [ ] I suggest that we should rename the index.html in the src directory to template.html 

Please feel free to leave a comment in case the changes won't be neccessary

**Comment by Dorcas126** [comment]
> Hi @Dorcas126, You have done an amazing job of setting up the files for the capstone projects. However, I would like to add a few changes to the webpack configuration before we merge it.
> 
> ##Changes
> 
> * [ ]  I would like to create a config file for development mode and production mode.
> * [ ]  I suggest that we should rename the index.html in the src directory to template.html
> 
> Please feel free to leave a comment in case the changes won't be neccessary

**Comment by Dorcas126** [comment]
> Hi @Dorcas126, You have done an amazing job of setting up the files for the capstone projects. However, I would like to add a few changes to the webpack configuration before we merge it.
> 
> ##Changes
> 
> * [ ]  I would like to create a config file for development mode and production mode.
> * [ ]  I suggest that we should rename the index.html in the src directory to template.html
> 
> Please feel free to leave a comment in case the changes won't be necessary

**Comment by Dorcas126** [comment]
> Hi @Dorcas126, You have done an amazing job of setting up the files for the capstone projects. However, I would like to add a few changes to the webpack configuration before we merge it.
> 
> ##Changes
> 
> * [ ]  I would like to create a config file for development mode and production mode.
> * [ ]  I suggest that we should rename the index.html in the src directory to template.html
> 
> Please feel free to leave a comment in case the changes won't be neccessary

Hi @AsumVictor well done on the changes you made 
it's really an amazing job 

You can make the remaining changes you requested👍

**Comment by AsumVictor** [comment]
Thank you @Dorcas126, we are ready to merge

**Pull request merged**
